set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

filetype plugin indent on     " required!

set nowrap        "don't wrap lines
set scrolloff=2         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

set backspace=indent,eol,start
                  " allow backspacing over everything in insert mode
set autoindent    " always set autoindenting on
set nocopyindent    " don't copy the previous indentation on autoindenting
set number        " always show line numbers
set shiftwidth=4
set showmatch     " set show matching parenthesis
"set smartindent
set ignorecase    " ignore case when searching
set smartcase     " ignore case if search pattern is all lowercase,
                  "    case-sensitive otherwise
set smarttab      " insert tabs on the start of a line according to
                  "    shiftwidth, not tabstop
"set tabstop=4
set expandtab     " tabs => spaces
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type

"set background=dark
" http://www.thegeekstuff.com/2009/04/ctags-taglist-vi-vim-editor-as-sourece-code-browser/
" http://amix.dk/blog/post/19329
set mouse=a
let Tlist_Ctags_Cmd = "/usr/bin/ctags"
let Tlist_WinWidth = 50
map <F7> :TlistToggle<cr>
map <F8> :!/usr/bin/ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

set noeb vb t_vb=       " Disable visual bells for the love of god

"This is for setting Makefiles with tabs not spaces
autocmd FileType make setlocal noexpandtab tabstop=8 softtabstop=8 shiftwidth=8
